modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
#issueTrackerURL = "https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
modId = "dyeable_levitite"
version = "${version}"
displayName = "Dyed Levitite"
#logoFile = "examplemod.png"
#credits = ""
authors = "Me!"
description = '''
h
'''

[[mixins]]
config = "dyeable_levitite.mixins.json"

[[dependencies.dyeable_levitite]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neo_version},)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dyeable_levitite]]
    modId = "minecraft"
    type = "required"
    versionRange = "[${minecraft_version}]"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.dyeable_levitite]]
modId = "aeronautics"
type = "required"
#versionRange = "[${minecraft_version}]"
ordering = "AFTER"
side = "BOTH"